FROM 850074925782.dkr.ecr.us-west-2.amazonaws.com/dockerproductionaws/microtrader-base
MAINTAINER Pankaj Jadhav <jadhavpankaj957@gmail.com>
LABEL application.component=microtrader-portfolio

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-portfolio-${app_version}-fat.jar /app/app.jar